#!/usr/bin/env bash
# Sync the fork with upstream druths/ark (mine-capstone#471).
#
# Runs on an operator machine with authenticated `gh`. Fetches upstream,
# creates `sync/ark-YYYY-MM-DD` from origin/main, merges upstream/main,
# pushes, and opens a PR so CI (talos-test) validates the merge before it
# reaches main. Never touches your checked-out branch's working tree
# beyond switching to the new sync branch.
#
# Exits 0 with a message when the fork already contains upstream (no PR
# possible or needed). On merge conflict it leaves the merge in progress
# on the sync branch and prints resolution guidance — conflicts mean the
# fork broke the additive-only rule (see deploy/README.md, "Upstream
# sync") or upstream touched deploy/, and a human must decide.
#
# Usage: deploy/scripts/sync-upstream.sh
set -Eeuo pipefail

UPSTREAM_URL="${UPSTREAM_URL:-https://github.com/druths/ark.git}"
UPSTREAM_BRANCH="${UPSTREAM_BRANCH:-main}"
BASE_BRANCH="${BASE_BRANCH:-main}"

die() {
    echo "sync-upstream.sh: error: $*" >&2
    exit 1
}

note() {
    echo "sync-upstream.sh: $*"
}

command -v gh >/dev/null 2>&1 || die "gh not found"
cd "$(git rev-parse --show-toplevel 2>/dev/null || true)" 2>/dev/null \
    || die "not inside a git repository"
[[ -z "$(git status --porcelain)" ]] || die "working tree is not clean"

# Documented remote setup: origin = mine-ai2/harness-ark, upstream =
# druths/ark. Add upstream if this clone doesn't have it yet.
if ! git remote get-url upstream >/dev/null 2>&1; then
    git remote add upstream "$UPSTREAM_URL"
    note "added remote: upstream = $UPSTREAM_URL"
fi

git fetch --quiet origin
git fetch --quiet upstream

if git merge-base --is-ancestor "upstream/$UPSTREAM_BRANCH" "origin/$BASE_BRANCH"; then
    note "already in sync: upstream/$UPSTREAM_BRANCH is fully contained in origin/$BASE_BRANCH"
    exit 0
fi

BRANCH="sync/ark-$(date +%Y-%m-%d)"
git rev-parse --verify --quiet "refs/heads/$BRANCH" >/dev/null \
    && die "local branch $BRANCH already exists — delete it or finish that sync first"
git ls-remote --exit-code origin "refs/heads/$BRANCH" >/dev/null 2>&1 \
    && die "remote branch $BRANCH already exists — finish that sync first"

incoming="$(git log --oneline "origin/$BASE_BRANCH..upstream/$UPSTREAM_BRANCH" | wc -l | tr -d ' ')"
note "syncing $incoming upstream commit(s) into $BRANCH"
git switch -c "$BRANCH" "origin/$BASE_BRANCH"

if ! git merge --no-edit "upstream/$UPSTREAM_BRANCH"; then
    cat >&2 <<EOF
sync-upstream.sh: MERGE CONFLICT — left in progress on $BRANCH.

A conflict means the fork edited something upstream also changed. Per the
fork rules (deploy/README.md, "Upstream sync"), MineAI-specifics live only
in deploy/ and the talos-* workflows, so for conflicts under ark/ prefer
the upstream side unless the change is one of the sanctioned extensions.

Resolve, then:
  git add -A && git commit --no-edit
  git push -u origin $BRANCH
  gh pr create --base $BASE_BRANCH --head $BRANCH
EOF
    exit 1
fi

git push -u origin "$BRANCH"
gh pr create \
    --base "$BASE_BRANCH" \
    --head "$BRANCH" \
    --title "Sync upstream ark ($(date +%Y-%m-%d))" \
    --body "$(
        printf 'Automated upstream sync (mine-capstone#471): merges %s commit(s) from druths/ark %s.\n\n' "$incoming" "$UPSTREAM_BRANCH"
        printf '```\n'
        git log --oneline "origin/$BASE_BRANCH..upstream/$UPSTREAM_BRANCH" | head -50
        printf '```\n\nGenerated by deploy/scripts/sync-upstream.sh.\n'
    )"
note "sync PR opened for $BRANCH"
